export const CARD_LENGTH_LIMIT = {
    CONCEPT_CARD_TERM_LENGTH_LIMIT: 100,
    CONCEPT_CARD_DEFINITION_LENGTH_LIMIT: 2000,
    STUDY_CARD_TITLE_LENGTH_LIMIT: 100,
    STUDY_CARD_DESCRIPTION_LENGTH_LIMIT: 200,
    STUDY_CARD_SCHOOL_LIMIT: 100
}
